"""Núcleo independente de interface para o protocolo de licenças ACT4."""

from .errors import (
    LicenseCoreError,
    LicenseExpiredError,
    LicenseFormatError,
    LicenseNotYetValidError,
    MachineMismatchError,
    SignatureVerificationError,
    UnknownKeyError,
    UnsupportedSchemaError,
)
from .protocol import (
    LICENSE_FILE_FORMAT,
    LICENSE_FILE_SUFFIX,
    LICENSE_SCHEMA,
    LicensePayload,
    PublicKeyRing,
    canonicalize_payload,
    issue_license,
    load_license_file,
    parse_license,
    verify_license,
)
from .state import (
    ClockTamperedError,
    ExpiredLicenseError,
    FeatureNotLicensedError,
    InvalidLicenseAccessError,
    LicenseAccessError,
    LicenseState,
    LicenseStatus,
    MachineMismatchAccessError,
    UnlicensedAccessError,
    evaluate_act4,
    invalid_status,
    require_feature,
    unlicensed_status,
)

__all__ = [
    "LICENSE_FILE_FORMAT",
    "LICENSE_FILE_SUFFIX",
    "LICENSE_SCHEMA",
    "ClockTamperedError",
    "ExpiredLicenseError",
    "FeatureNotLicensedError",
    "InvalidLicenseAccessError",
    "LicenseAccessError",
    "LicenseCoreError",
    "LicenseExpiredError",
    "LicenseFormatError",
    "LicenseNotYetValidError",
    "LicensePayload",
    "LicenseState",
    "LicenseStatus",
    "MachineMismatchError",
    "MachineMismatchAccessError",
    "PublicKeyRing",
    "SignatureVerificationError",
    "UnknownKeyError",
    "UnsupportedSchemaError",
    "UnlicensedAccessError",
    "canonicalize_payload",
    "evaluate_act4",
    "invalid_status",
    "issue_license",
    "load_license_file",
    "parse_license",
    "require_feature",
    "unlicensed_status",
    "verify_license",
]
